# Generated by Django 4.2.2 on 2023-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_tracker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='length_in_minutes',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
