# Generated by Django 4.2.2 on 2023-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_tracker_length_in_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='length_in_minutes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
