# Generated by Django 4.2.2 on 2023-06-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_tracker_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='date',
        ),
    ]
