# Generated by Django 4.2.2 on 2023-06-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_tracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='category',
            field=models.CharField(choices=[('FIT', 'Fitness'), ('SL', 'Sleep'), ('HW', 'Health and Wellness'), ('QBH', 'Quit a Bad Habit'), ('HH', 'Household')], max_length=50),
        ),
    ]
