# Generated by Django 4.2.2 on 2023-06-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_tracker_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('HC', 'healthcare'), ('ED', 'education'), ('TECH', 'tech industry'), ('LAW', 'law'), ('RETAIL', 'retail'), ('CS', 'customer service'), ('SI', 'service industry'), ('SE', 'self employed'), ('UNEMP', 'unemployed'), ('POG', 'parent or guardian'), ('ST', 'student')], max_length=30),
        ),
    ]
