# Generated by Django 4.2.2 on 2023-06-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_user_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('HC', 'healthcare'), ('ED', 'education'), ('TECH', 'tech industry'), ('LAW', 'law'), ('RETAIL', 'retail'), ('CS', 'customer service'), ('SI', 'service industry'), ('SE', 'self employed'), ('UNEMP', 'unemployed'), ('POG', 'parent or guardian'), ('ST', 'student'), ('OT', 'other')], max_length=30),
        ),
    ]
