# Generated by Django 4.2.2 on 2023-06-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_remove_tracker_length_in_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='target',
            new_name='target_number',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='category',
        ),
        migrations.AddField(
            model_name='tracker',
            name='target_action',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
