# Generated by Django 4.2.2 on 2023-06-07 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_rename_target_action_tracker_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='action',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
