# Generated by Django 4.2.2 on 2023-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_remove_tracker_target_number_tracker_goal_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='goal_met',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'yes')], default=False),
        ),
    ]
