# Generated by Django 4.2.2 on 2023-06-07 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0015_alter_tracker_goal_met'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('goal_met', models.BooleanField(choices=[(False, 'No'), (True, 'yes')], default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='goal_met',
        ),
    ]
