# Generated by Django 4.2.2 on 2023-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0017_record_tracker_alter_record_goal_met'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='entry_number',
            field=models.IntegerField(default=1),
        ),
    ]
