# Generated by Django 4.2.2 on 2023-06-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0018_record_entry_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('entry_number', 'date')},
        ),
    ]
