# Generated by Django 4.2.2 on 2023-06-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0019_alter_record_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
    ]
