# Generated by Django 4.2.2 on 2023-06-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0020_alter_record_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='entry_number',
        ),
    ]
