# Generated by Django 4.2.2 on 2023-06-08 13:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0021_remove_record_entry_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='record',
            managers=[
                ('date_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
