# Generated by Django 4.2.2 on 2023-06-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0022_alter_record_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_number',
            field=models.IntegerField(default=0),
        ),
    ]
