# Generated by Django 4.2.2 on 2023-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0023_record_record_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('date', 'tracker'), name='unique_constraint'),
        ),
    ]
