# Generated by Django 4.2.2 on 2023-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0024_record_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('occupation', models.CharField(choices=[('HC', 'healthcare'), ('ED', 'education'), ('TECH', 'tech industry'), ('LAW', 'law'), ('RETAIL', 'retail'), ('CS', 'customer service'), ('SI', 'service industry'), ('SE', 'self employed'), ('UNEMP', 'unemployed'), ('POG', 'parent or guardian'), ('ST', 'student'), ('OT', 'other')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
    ]
