# Generated by Django 4.2.2 on 2023-06-08 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0026_remove_user_birthdate_profile_birthdate_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
