# Generated by Django 4.2.2 on 2023-06-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0029_alter_user_options_remove_record_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='record',
            managers=[
            ],
        ),
    ]
