# Generated by Django 4.2.2 on 2023-06-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0031_remove_profile_user_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='profile',
        ),
    ]
