# Generated by Django 4.2.2 on 2023-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0034_alter_record_goal_met_follower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_constraint',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='user_constraint'),
        ),
    ]
